docs: Update README.md installation instructions
ansh/bionic-reading pull request #65
Opened 2022-05-25 16:50 UTC by meetbryce

2022-05-25 18:28 UTC, FahimFBA approved these changes
Thanks for adding the lines 13, 14 and 15.
These 3 lines are really necessary.

2022-05-25 18:35 UTC, FahimFBA requested changes

2022-05-25 18:35 UTC, FahimFBA commented on README.md
> +4. Open the folder in the command line
```suggestion
4. Open the folder in the command line (Suggesting to use bash terminal in case you are using the Windows operating system).
```

2022-05-25 18:35 UTC, FahimFBA commented on README.md
>  3. Right click the ZIP file > Extract All > OK
```suggestion
3. Right click the ZIP file > Extract All > OK.
```

2022-05-25 18:35 UTC, FahimFBA commented on README.md
> +6. Open Chrome > go to this link chrome://extensions/
```suggestion
6. Open Chrome > go to this link `chrome://extensions/` .
```

2022-05-25 18:35 UTC, FahimFBA commented on README.md
> +5. Run `yarn install; yarn build;`
```suggestion
5. Run `yarn install; yarn build;` .
```

2022-05-26 01:28 UTC, X140Yu commented
Hi @meetbryce @FahimFBA

I created a release workflow, artifacts can be produced with every tag pushed, so that users don't need to build themselves.

Can you change the doc based on the new workflow, much appreciated 🙏

2022-05-27 09:10 UTC, X140Yu approved these changes

2022-05-27 09:10 UTC, merged